-- =============================================================
-- CAH Cinema background seed data
-- -------------------------------------------------------------
-- Run this after cah_cinema.sql when you need demo/test data.
-- This script is idempotent and intentionally avoids transactional
-- tables generated by user activity: bookings, tickets, food_orders,
-- payment_confirmations, invoices, pending_ticket_items,
-- booking_food_draft_items, food_order_items, and outbox_events.
-- =============================================================

BEGIN;

-- =============================================================
-- 1. Lookup data
-- =============================================================

INSERT INTO roles (role_name) VALUES ('ROLE_USER'), ('ROLE_ADMIN')
ON CONFLICT (role_name) DO NOTHING;

INSERT INTO genres (name, created_at, is_deleted)
SELECT v.name, CURRENT_TIMESTAMP, FALSE
FROM (VALUES
    ('Action'),
    ('Adventure'),
    ('Animation'),
    ('Comedy'),
    ('Crime'),
    ('Drama'),
    ('Family'),
    ('Fantasy'),
    ('Horror'),
    ('Musical'),
    ('Mystery'),
    ('Romance'),
    ('Science Fiction'),
    ('Thriller'),
    ('War'),
    ('Documentary')
) AS v(name)
WHERE NOT EXISTS (
    SELECT 1 FROM genres g WHERE LOWER(g.name) = LOWER(v.name) AND g.is_deleted = FALSE
);

INSERT INTO seat_types (type_name, price_multiplier)
SELECT v.type_name, v.price_multiplier
FROM (VALUES
    ('NORMAL', 1.00),
    ('VIP', 1.25),
    ('COUPLE', 1.80),
    ('AISLE', 0.00)
) AS v(type_name, price_multiplier)
WHERE NOT EXISTS (
    SELECT 1 FROM seat_types st WHERE st.type_name = v.type_name
);

INSERT INTO price_configs (day_type, time_slot, movie_format, multiplier)
SELECT v.day_type, v.time_slot, v.movie_format, v.multiplier
FROM (VALUES
    ('WEEKDAY', NULL, NULL, 1.00),
    ('WEEKEND', NULL, NULL, 1.20),
    ('HOLIDAY', NULL, NULL, 1.50),
    (NULL, 'MORNING', NULL, 0.90),
    (NULL, 'AFTERNOON', NULL, 1.00),
    (NULL, 'EVENING', NULL, 1.15),
    (NULL, NULL, '2D', 1.00),
    (NULL, NULL, '3D', 1.20),
    (NULL, NULL, 'IMAX', 1.45)
) AS v(day_type, time_slot, movie_format, multiplier)
WHERE NOT EXISTS (
    SELECT 1
    FROM price_configs pc
    WHERE pc.day_type IS NOT DISTINCT FROM v.day_type
      AND pc.time_slot IS NOT DISTINCT FROM v.time_slot
      AND pc.movie_format IS NOT DISTINCT FROM v.movie_format
);

INSERT INTO holidays (name, holiday_date, is_recurring)
SELECT v.name, v.holiday_date, v.is_recurring
FROM (VALUES
    ('Tết Dương lịch', DATE '2026-01-01', TRUE),
    ('Valentine', DATE '2026-02-14', TRUE),
    ('Giỗ Tổ Hùng Vương 2026', DATE '2026-04-18', FALSE),
    ('Ngày Giải phóng miền Nam', DATE '2026-04-30', TRUE),
    ('Ngày Quốc tế Lao động', DATE '2026-05-01', TRUE),
    ('Quốc khánh Việt Nam', DATE '2026-09-02', TRUE),
    ('Giáng sinh', DATE '2026-12-25', TRUE)
) AS v(name, holiday_date, is_recurring)
WHERE NOT EXISTS (
    SELECT 1 FROM holidays h WHERE h.name = v.name AND h.holiday_date = v.holiday_date
);

-- =============================================================
-- 2. Cinemas, rooms, and seats
-- =============================================================

INSERT INTO cinemas (name, address, image_url, hotline, created_at, is_deleted)
SELECT v.name, v.address, v.image_url, v.hotline, CURRENT_TIMESTAMP, FALSE
FROM (VALUES
    ('CAH Cinema Landmark 81', 'Tầng B1, Vincom Center Landmark 81, 720A Điện Biên Phủ, Bình Thạnh, TP.HCM', 'https://cdn.cah.local/cinemas/landmark81.jpg', '028 7300 8181'),
    ('CAH Cinema Sư Vạn Hạnh', 'Tầng 6, Vạn Hạnh Mall, 11 Sư Vạn Hạnh, Quận 10, TP.HCM', 'https://cdn.cah.local/cinemas/su-van-hanh.jpg', '028 7300 1010'),
    ('CAH Cinema Crescent Mall', 'Tầng 5, Crescent Mall, 101 Tôn Dật Tiên, Quận 7, TP.HCM', 'https://cdn.cah.local/cinemas/crescent-mall.jpg', '028 7300 0707'),
    ('CAH Cinema Vincom Bà Triệu', 'Tầng 6, Vincom Center, 191 Bà Triệu, Hai Bà Trưng, Hà Nội', 'https://cdn.cah.local/cinemas/vincom-ba-trieu.jpg', '024 7300 1919'),
    ('CAH Cinema Royal City', 'Tầng B2, Royal City, 72A Nguyễn Trãi, Thanh Xuân, Hà Nội', 'https://cdn.cah.local/cinemas/royal-city.jpg', '024 7300 7272'),
    ('CAH Cinema Đà Nẵng Riverside', 'Tầng 4, Indochina Riverside Mall, 74 Bạch Đằng, Hải Châu, Đà Nẵng', 'https://cdn.cah.local/cinemas/da-nang-riverside.jpg', '0236 7300 7474')
) AS v(name, address, image_url, hotline)
WHERE NOT EXISTS (
    SELECT 1 FROM cinemas c WHERE c.name = v.name AND c.is_deleted = FALSE
);

INSERT INTO rooms (cinema_id, room_name, is_deleted)
SELECT c.cinema_id, v.room_name, FALSE
FROM cinemas c
CROSS JOIN (VALUES
    ('Phòng 01 - Standard'),
    ('Phòng 02 - Premium'),
    ('Phòng 03 - IMAX')
) AS v(room_name)
WHERE c.name IN (
    'CAH Cinema Landmark 81',
    'CAH Cinema Sư Vạn Hạnh',
    'CAH Cinema Crescent Mall',
    'CAH Cinema Vincom Bà Triệu',
    'CAH Cinema Royal City',
    'CAH Cinema Đà Nẵng Riverside'
)
AND NOT EXISTS (
    SELECT 1 FROM rooms r
    WHERE r.cinema_id = c.cinema_id
      AND r.room_name = v.room_name
      AND r.is_deleted = FALSE
);

DO $$
DECLARE
    row_column_name TEXT;
    col_column_name TEXT;
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'seats'
          AND column_name = 'seat_row'
    ) AND EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'seats'
          AND column_name = 'seat_col'
    ) THEN
        row_column_name := 'seat_row';
        col_column_name := 'seat_col';
    ELSIF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'seats'
          AND column_name = 'row'
    ) AND EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = 'seats'
          AND column_name = 'col'
    ) THEN
        row_column_name := 'row';
        col_column_name := 'col';
    ELSE
        RAISE EXCEPTION 'Cannot seed seats: table %.seats must have either (seat_row, seat_col) from cah_cinema.sql or legacy (row, col) columns', current_schema();
    END IF;

    EXECUTE format($seed$
        WITH seat_type_ids AS (
            SELECT
                MAX(CASE WHEN type_name = 'NORMAL' THEN seat_type_id END) AS normal_id,
                MAX(CASE WHEN type_name = 'VIP' THEN seat_type_id END) AS vip_id,
                MAX(CASE WHEN type_name = 'COUPLE' THEN seat_type_id END) AS couple_id,
                MAX(CASE WHEN type_name = 'AISLE' THEN seat_type_id END) AS aisle_id
            FROM seat_types
        ), target_rooms AS (
            SELECT r.room_id, r.room_name
            FROM rooms r
            JOIN cinemas c ON c.cinema_id = r.cinema_id
            WHERE c.name LIKE 'CAH Cinema%%'
              AND r.is_deleted = FALSE
        ), physical_seats AS (
            SELECT
                tr.room_id,
                row_no::NUMERIC(5,1) AS generated_seat_row,
                col_no::NUMERIC(5,1) AS generated_seat_col,
                CASE
                    WHEN row_no = 8 THEN sti.couple_id
                    WHEN row_no BETWEEN 4 AND 7 THEN sti.vip_id
                    ELSE sti.normal_id
                END AS seat_type_id,
                CASE WHEN row_no = 1 AND col_no IN (1, 12) THEN 'PREPARE' ELSE 'ACTIVE' END AS status
            FROM target_rooms tr
            CROSS JOIN seat_type_ids sti
            CROSS JOIN generate_series(1, 8) AS row_no
            CROSS JOIN generate_series(1, 12) AS col_no
        ), vertical_aisles AS (
            SELECT
                tr.room_id,
                row_no::NUMERIC(5,1) AS generated_seat_row,
                6.5::NUMERIC(5,1) AS generated_seat_col,
                sti.aisle_id AS seat_type_id,
                'ACTIVE' AS status
            FROM target_rooms tr
            CROSS JOIN seat_type_ids sti
            CROSS JOIN generate_series(1, 8) AS row_no
        ), horizontal_aisles AS (
            SELECT
                tr.room_id,
                4.5::NUMERIC(5,1) AS generated_seat_row,
                col_no::NUMERIC(5,1) AS generated_seat_col,
                sti.aisle_id AS seat_type_id,
                'ACTIVE' AS status
            FROM target_rooms tr
            CROSS JOIN seat_type_ids sti
            CROSS JOIN generate_series(1, 12) AS col_no
        ), all_seats AS (
            SELECT * FROM physical_seats
            UNION ALL
            SELECT * FROM vertical_aisles
            UNION ALL
            SELECT * FROM horizontal_aisles
        )
        INSERT INTO seats (room_id, %I, %I, seat_type_id, status, is_deleted)
        SELECT s.room_id, s.generated_seat_row, s.generated_seat_col, s.seat_type_id, s.status, FALSE
        FROM all_seats s
        WHERE NOT EXISTS (
            SELECT 1 FROM seats existing
            WHERE existing.room_id = s.room_id
              AND existing.%I = s.generated_seat_row
              AND existing.%I = s.generated_seat_col
              AND existing.is_deleted = FALSE
        )
    $seed$, row_column_name, col_column_name, row_column_name, col_column_name);
END $$;

-- =============================================================
-- 3. Movies and genres
-- =============================================================

WITH movie_seed AS (
    SELECT * FROM (VALUES
        ('Michael', 'Chân dung điện ảnh về Michael Jackson, theo dấu hành trình từ thần đồng âm nhạc đến biểu tượng văn hóa toàn cầu.', 130, DATE '2026-04-24', 'Antoine Fuqua', 'Jaafar Jackson, Colman Domingo, Nia Long, Miles Teller', 'T13', 'https://image.tmdb.org/t/p/w500/sample-michael-2026.jpg', 'https://www.youtube.com/watch?v=sample-michael'),
        ('Mortal Kombat II', 'Các chiến binh Earthrealm bước vào giải đấu sinh tử mới, nơi danh dự và số phận thế giới được đặt lên bàn cân.', 115, DATE '2026-05-08', 'Simon McQuoid', 'Karl Urban, Lewis Tan, Jessica McNamee, Mehcad Brooks', 'T18', 'https://image.tmdb.org/t/p/w500/sample-mortal-kombat-ii.jpg', 'https://www.youtube.com/watch?v=sample-mk2'),
        ('The Mandalorian and Grogu', 'Din Djarin và Grogu trở lại trong chuyến phiêu lưu màn ảnh rộng giữa những tàn dư của Đế chế.', 120, DATE '2026-05-22', 'Jon Favreau', 'Pedro Pascal, Sigourney Weaver', 'T13', 'https://image.tmdb.org/t/p/w500/sample-mandalorian-grogu.jpg', 'https://www.youtube.com/watch?v=sample-mando'),
        ('The Sheep Detectives', 'Một đàn cừu tinh quái tự lập đội điều tra khi trang trại yên bình bỗng xuất hiện vụ án bí ẩn.', 103, DATE '2026-05-15', 'Kyle Balda', 'Hugh Jackman, Emma Thompson, Nicholas Braun', 'K', 'https://image.tmdb.org/t/p/w500/sample-sheep-detectives.jpg', 'https://www.youtube.com/watch?v=sample-sheep'),
        ('Yêu Nữ Thích Hàng Hiệu 2', 'Thế giới thời trang xa hoa trở lại với những cuộc đối đầu sắc sảo, hài hước và đầy tham vọng.', 110, DATE '2026-05-29', 'David Frankel', 'Meryl Streep, Anne Hathaway, Emily Blunt', 'T13', 'https://image.tmdb.org/t/p/w500/sample-devil-wears-prada-2.jpg', 'https://www.youtube.com/watch?v=sample-fashion'),
        ('Doraemon: Nobita Và Cuộc Phiêu Lưu Ở Thế Giới Tranh', 'Nobita cùng Doraemon bước vào thế giới tranh vẽ rực rỡ để giải cứu những người bạn mới.', 105, DATE '2026-05-23', 'Yukiyo Teramoto', 'Wasabi Mizuta, Megumi Oohara, Yumi Kakazu', 'P', 'https://image.tmdb.org/t/p/w500/sample-doraemon-art-world.jpg', 'https://www.youtube.com/watch?v=sample-doraemon'),
        ('Thám Tử Kiên: Kỳ Án Không Đầu', 'Một vụ án ly kỳ trong khung cảnh cổ trang Việt Nam buộc thám tử Kiên lần theo những manh mối rợn người.', 131, DATE '2026-04-30', 'Victor Vũ', 'Quốc Huy, Đinh Ngọc Diệp, Minh Anh', 'T16', 'https://image.tmdb.org/t/p/w500/sample-tham-tu-kien.jpg', 'https://www.youtube.com/watch?v=sample-kien'),
        ('Lật Mặt 9: Vòng Xoáy Gia Đình', 'Một biến cố bất ngờ kéo cả gia đình vào chuỗi lựa chọn sinh tử giữa tình thân và sự thật.', 124, DATE '2026-04-26', 'Lý Hải', 'Huy Khánh, Mạc Văn Khoa, Khả Ngân', 'T13', 'https://image.tmdb.org/t/p/w500/sample-lat-mat-9.jpg', 'https://www.youtube.com/watch?v=sample-latmat'),
        ('Supergirl: Woman of Tomorrow', 'Kara Zor-El đối mặt hành trình vũ trụ khắc nghiệt để tìm lại niềm tin và bảo vệ những điều cô yêu quý.', 125, DATE '2026-06-26', 'Craig Gillespie', 'Milly Alcock, Matthias Schoenaerts, Eve Ridley', 'T13', 'https://image.tmdb.org/t/p/w500/sample-supergirl-2026.jpg', 'https://www.youtube.com/watch?v=sample-supergirl'),
        ('Toy Story 5', 'Woody, Buzz và những món đồ chơi thân quen đứng trước thử thách mới trong thời đại công nghệ.', 100, DATE '2026-06-19', 'Andrew Stanton', 'Tom Hanks, Tim Allen, Joan Cusack', 'P', 'https://image.tmdb.org/t/p/w500/sample-toy-story-5.jpg', 'https://www.youtube.com/watch?v=sample-toystory5'),
        ('Moana: Live Action', 'Moana lên đường vượt đại dương trong phiên bản live-action giàu âm nhạc và sắc màu Polynesia.', 118, DATE '2026-07-10', 'Thomas Kail', 'Catherine Lagaʻaia, Dwayne Johnson', 'P', 'https://image.tmdb.org/t/p/w500/sample-moana-live-action.jpg', 'https://www.youtube.com/watch?v=sample-moana'),
        ('Scream 7', 'Một chương mới của Ghostface đưa những bí mật cũ trở lại, khốc liệt và khó đoán hơn bao giờ hết.', 112, DATE '2026-02-27', 'Kevin Williamson', 'Neve Campbell, Courteney Cox, Mason Gooding', 'T18', 'https://image.tmdb.org/t/p/w500/sample-scream-7.jpg', 'https://www.youtube.com/watch?v=sample-scream7'),
        ('Project Hail Mary', 'Một phi hành gia tỉnh dậy đơn độc trên tàu vũ trụ và phải cứu Trái Đất khỏi thảm họa liên sao.', 138, DATE '2026-03-20', 'Phil Lord, Christopher Miller', 'Ryan Gosling, Sandra Hüller, Milana Vayntrub', 'T13', 'https://image.tmdb.org/t/p/w500/sample-project-hail-mary.jpg', 'https://www.youtube.com/watch?v=sample-hailmary'),
        ('Minions & Monsters', 'Những chú Minion vô tình đánh thức một thế giới quái vật đáng yêu và hỗn loạn.', 92, DATE '2026-06-05', 'Pierre Coffin', 'Steve Carell, Pierre Coffin, Taraji P. Henson', 'P', 'https://image.tmdb.org/t/p/w500/sample-minions-monsters.jpg', 'https://www.youtube.com/watch?v=sample-minions'),
        ('Thẩm Mỹ Viện Âm Phủ', 'Một spa bí ẩn hứa hẹn vẻ đẹp hoàn hảo nhưng ẩn sau là cái giá khiến khách hàng không thể quay đầu.', 101, DATE '2026-05-01', 'Lê Bình Giang', 'Kaity Nguyễn, Thu Trang, Quốc Trường', 'T18', 'https://image.tmdb.org/t/p/w500/sample-tham-my-vien-am-phu.jpg', 'https://www.youtube.com/watch?v=sample-spa'),
        ('Trạng Quỳnh Nhí: Truyền Thuyết Hồ Sen', 'Trạng Quỳnh lúc nhỏ cùng nhóm bạn giải mã truyền thuyết hồ sen trong một chuyến phiêu lưu hài hước.', 96, DATE '2026-05-16', 'Đức Thịnh', 'Hạo Khang, Bảo Ngọc, Đại Nghĩa', 'P', 'https://image.tmdb.org/t/p/w500/sample-trang-quynh-nhi.jpg', 'https://www.youtube.com/watch?v=sample-quynh'),
        ('Ballerina', 'Một sát thủ trẻ được huấn luyện trong thế giới ngầm bước vào hành trình trả thù lạnh lùng.', 125, DATE '2025-06-06', 'Len Wiseman', 'Ana de Armas, Keanu Reeves, Ian McShane', 'T18', 'https://image.tmdb.org/t/p/w500/sample-ballerina.jpg', 'https://www.youtube.com/watch?v=sample-ballerina'),
        ('Mission: Impossible - The Final Reckoning', 'Ethan Hunt đối mặt nhiệm vụ cuối cùng, nơi mỗi lựa chọn đều có thể thay đổi trật tự thế giới.', 169, DATE '2025-05-23', 'Christopher McQuarrie', 'Tom Cruise, Hayley Atwell, Ving Rhames', 'T13', 'https://image.tmdb.org/t/p/w500/sample-mi-final-reckoning.jpg', 'https://www.youtube.com/watch?v=sample-mi'),
        ('How to Train Your Dragon', 'Hiccup và Toothless chứng minh tình bạn có thể thay đổi định kiến giữa người Viking và loài rồng.', 116, DATE '2025-06-13', 'Dean DeBlois', 'Mason Thames, Nico Parker, Gerard Butler', 'K', 'https://image.tmdb.org/t/p/w500/sample-httyd-live-action.jpg', 'https://www.youtube.com/watch?v=sample-dragon'),
        ('Elio', 'Một cậu bé được đưa tới liên minh thiên hà và bất đắc dĩ trở thành đại diện của Trái Đất.', 98, DATE '2025-06-20', 'Adrian Molina, Domee Shi', 'Yonas Kibreab, Zoe Saldaña, Brad Garrett', 'P', 'https://image.tmdb.org/t/p/w500/sample-elio.jpg', 'https://www.youtube.com/watch?v=sample-elio'),
        ('F1 The Movie', 'Một tay đua kỳ cựu trở lại đường đua Công thức 1 để dẫn dắt tài năng trẻ trong mùa giải khốc liệt.', 136, DATE '2025-06-27', 'Joseph Kosinski', 'Brad Pitt, Damson Idris, Kerry Condon', 'T13', 'https://image.tmdb.org/t/p/w500/sample-f1-movie.jpg', 'https://www.youtube.com/watch?v=sample-f1'),
        ('Jurassic World Rebirth', 'Một nhóm thám hiểm tiến vào khu vực biệt lập để tìm kiếm đột phá y học giữa những loài khủng long nguy hiểm.', 134, DATE '2025-07-02', 'Gareth Edwards', 'Scarlett Johansson, Mahershala Ali, Jonathan Bailey', 'T13', 'https://image.tmdb.org/t/p/w500/sample-jurassic-rebirth.jpg', 'https://www.youtube.com/watch?v=sample-jurassic'),
        ('The Fantastic Four: First Steps', 'Gia đình siêu anh hùng đầu tiên của Marvel đối mặt hiểm họa vũ trụ đe dọa Trái Đất.', 118, DATE '2025-07-25', 'Matt Shakman', 'Pedro Pascal, Vanessa Kirby, Joseph Quinn', 'T13', 'https://image.tmdb.org/t/p/w500/sample-fantastic-four.jpg', 'https://www.youtube.com/watch?v=sample-f4'),
        ('Wicked: For Good', 'Câu chuyện tình bạn, lựa chọn và định mệnh ở xứ Oz tiếp tục trong hồi kết giàu cảm xúc.', 140, DATE '2025-11-21', 'Jon M. Chu', 'Cynthia Erivo, Ariana Grande, Jonathan Bailey', 'K', 'https://image.tmdb.org/t/p/w500/sample-wicked-for-good.jpg', 'https://www.youtube.com/watch?v=sample-wicked2'),
        ('Avatar: Fire and Ash', 'Gia đình Sully khám phá những vùng đất mới của Pandora, nơi ngọn lửa và tro tàn hé lộ hiểm họa khác.', 190, DATE '2025-12-19', 'James Cameron', 'Sam Worthington, Zoe Saldaña, Sigourney Weaver', 'T13', 'https://image.tmdb.org/t/p/w500/sample-avatar-fire-ash.jpg', 'https://www.youtube.com/watch?v=sample-avatar3'),
        ('The Batman Part II', 'Gotham chìm sâu hơn vào bóng tối khi Batman lần theo một âm mưu mới trong thành phố mục ruỗng.', 150, DATE '2026-10-02', 'Matt Reeves', 'Robert Pattinson, Jeffrey Wright, Andy Serkis', 'T16', 'https://image.tmdb.org/t/p/w500/sample-batman-part-ii.jpg', 'https://www.youtube.com/watch?v=sample-batman2'),
        ('Frozen 3', 'Elsa, Anna và những người bạn bước vào hành trình mới để hiểu sâu hơn về phép thuật của Arendelle.', 105, DATE '2026-11-25', 'Jennifer Lee', 'Idina Menzel, Kristen Bell, Josh Gad', 'P', 'https://image.tmdb.org/t/p/w500/sample-frozen-3.jpg', 'https://www.youtube.com/watch?v=sample-frozen3'),
        ('The Hunger Games: Sunrise on the Reaping', 'Câu chuyện tiền truyện về kỳ Hunger Games thứ 50 mở ra góc nhìn mới về Panem.', 135, DATE '2026-11-20', 'Francis Lawrence', 'TBA', 'T16', 'https://image.tmdb.org/t/p/w500/sample-sunrise-reaping.jpg', 'https://www.youtube.com/watch?v=sample-hunger-games')
    ) AS m(title, description, duration, release_date, director_name, actor_list, age_rating, poster_url, trailer_url)
)
INSERT INTO movies (title, description, duration, release_date, director_name, actor_list, age_rating, poster_url, trailer_url, created_at, updated_at, is_deleted)
SELECT ms.title, ms.description, ms.duration, ms.release_date, ms.director_name, ms.actor_list, ms.age_rating, ms.poster_url, ms.trailer_url, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE
FROM movie_seed ms
WHERE NOT EXISTS (
    SELECT 1 FROM movies m
    WHERE LOWER(m.title) = LOWER(ms.title)
      AND m.release_date = ms.release_date
      AND m.is_deleted = FALSE
);

WITH links(title, genre_name) AS (
    VALUES
        ('Michael', 'Drama'), ('Michael', 'Musical'),
        ('Mortal Kombat II', 'Action'), ('Mortal Kombat II', 'Adventure'), ('Mortal Kombat II', 'Fantasy'),
        ('The Mandalorian and Grogu', 'Adventure'), ('The Mandalorian and Grogu', 'Science Fiction'), ('The Mandalorian and Grogu', 'Action'),
        ('The Sheep Detectives', 'Animation'), ('The Sheep Detectives', 'Comedy'), ('The Sheep Detectives', 'Family'), ('The Sheep Detectives', 'Mystery'),
        ('Yêu Nữ Thích Hàng Hiệu 2', 'Comedy'), ('Yêu Nữ Thích Hàng Hiệu 2', 'Drama'),
        ('Doraemon: Nobita Và Cuộc Phiêu Lưu Ở Thế Giới Tranh', 'Animation'), ('Doraemon: Nobita Và Cuộc Phiêu Lưu Ở Thế Giới Tranh', 'Adventure'), ('Doraemon: Nobita Và Cuộc Phiêu Lưu Ở Thế Giới Tranh', 'Family'),
        ('Thám Tử Kiên: Kỳ Án Không Đầu', 'Mystery'), ('Thám Tử Kiên: Kỳ Án Không Đầu', 'Thriller'), ('Thám Tử Kiên: Kỳ Án Không Đầu', 'Drama'),
        ('Lật Mặt 9: Vòng Xoáy Gia Đình', 'Action'), ('Lật Mặt 9: Vòng Xoáy Gia Đình', 'Drama'), ('Lật Mặt 9: Vòng Xoáy Gia Đình', 'Thriller'),
        ('Supergirl: Woman of Tomorrow', 'Action'), ('Supergirl: Woman of Tomorrow', 'Adventure'), ('Supergirl: Woman of Tomorrow', 'Science Fiction'),
        ('Toy Story 5', 'Animation'), ('Toy Story 5', 'Comedy'), ('Toy Story 5', 'Family'),
        ('Moana: Live Action', 'Adventure'), ('Moana: Live Action', 'Family'), ('Moana: Live Action', 'Musical'),
        ('Scream 7', 'Horror'), ('Scream 7', 'Mystery'), ('Scream 7', 'Thriller'),
        ('Project Hail Mary', 'Adventure'), ('Project Hail Mary', 'Drama'), ('Project Hail Mary', 'Science Fiction'),
        ('Minions & Monsters', 'Animation'), ('Minions & Monsters', 'Comedy'), ('Minions & Monsters', 'Family'),
        ('Thẩm Mỹ Viện Âm Phủ', 'Horror'), ('Thẩm Mỹ Viện Âm Phủ', 'Thriller'),
        ('Trạng Quỳnh Nhí: Truyền Thuyết Hồ Sen', 'Comedy'), ('Trạng Quỳnh Nhí: Truyền Thuyết Hồ Sen', 'Family'), ('Trạng Quỳnh Nhí: Truyền Thuyết Hồ Sen', 'Adventure'),
        ('Ballerina', 'Action'), ('Ballerina', 'Thriller'),
        ('Mission: Impossible - The Final Reckoning', 'Action'), ('Mission: Impossible - The Final Reckoning', 'Adventure'), ('Mission: Impossible - The Final Reckoning', 'Thriller'),
        ('How to Train Your Dragon', 'Adventure'), ('How to Train Your Dragon', 'Family'), ('How to Train Your Dragon', 'Fantasy'),
        ('Elio', 'Animation'), ('Elio', 'Adventure'), ('Elio', 'Family'), ('Elio', 'Science Fiction'),
        ('F1 The Movie', 'Action'), ('F1 The Movie', 'Drama'),
        ('Jurassic World Rebirth', 'Action'), ('Jurassic World Rebirth', 'Adventure'), ('Jurassic World Rebirth', 'Science Fiction'),
        ('The Fantastic Four: First Steps', 'Action'), ('The Fantastic Four: First Steps', 'Adventure'), ('The Fantastic Four: First Steps', 'Science Fiction'),
        ('Wicked: For Good', 'Fantasy'), ('Wicked: For Good', 'Musical'), ('Wicked: For Good', 'Romance'),
        ('Avatar: Fire and Ash', 'Action'), ('Avatar: Fire and Ash', 'Adventure'), ('Avatar: Fire and Ash', 'Science Fiction'),
        ('The Batman Part II', 'Action'), ('The Batman Part II', 'Crime'), ('The Batman Part II', 'Drama'),
        ('Frozen 3', 'Animation'), ('Frozen 3', 'Family'), ('Frozen 3', 'Musical'),
        ('The Hunger Games: Sunrise on the Reaping', 'Action'), ('The Hunger Games: Sunrise on the Reaping', 'Drama'), ('The Hunger Games: Sunrise on the Reaping', 'Science Fiction')
)
INSERT INTO movie_genres (movie_id, genre_id)
SELECT m.movie_id, g.genre_id
FROM links l
JOIN movies m ON LOWER(m.title) = LOWER(l.title) AND m.is_deleted = FALSE
JOIN genres g ON LOWER(g.name) = LOWER(l.genre_name) AND g.is_deleted = FALSE
ON CONFLICT (movie_id, genre_id) DO NOTHING;

-- =============================================================
-- 4. Foods and vouchers
-- =============================================================

INSERT INTO foods (name, description, price, category, image_url, is_available, is_deleted)
SELECT v.name, v.description, v.price, v.category, v.image_url, v.is_available, FALSE
FROM (VALUES
    ('Combo Bắp Nước Classic', '01 bắp ngọt lớn và 02 nước ngọt size M.', 119000.00, 'Combo', 'https://cdn.cah.local/foods/combo-classic.jpg', TRUE),
    ('Combo Couple Sweet', '01 bắp caramel lớn và 02 nước ngọt size L.', 149000.00, 'Combo', 'https://cdn.cah.local/foods/combo-couple.jpg', TRUE),
    ('Combo Family Weekend', '02 bắp lớn, 04 nước ngọt size M và 01 snack khoai tây.', 249000.00, 'Combo', 'https://cdn.cah.local/foods/combo-family.jpg', TRUE),
    ('Combo Doraemon Kids', '01 bắp nhỏ, 01 nước trái cây và 01 sticker nhân vật.', 89000.00, 'Combo', 'https://cdn.cah.local/foods/combo-kids.jpg', TRUE),
    ('Combo IMAX Premium', '01 bắp phô mai lớn, 02 nước size L và 02 hotdog.', 219000.00, 'Combo', 'https://cdn.cah.local/foods/combo-imax.jpg', TRUE),
    ('Bắp Ngọt Lớn', 'Bắp rang bơ vị truyền thống size L.', 69000.00, 'Food', 'https://cdn.cah.local/foods/popcorn-butter.jpg', TRUE),
    ('Bắp Caramel Lớn', 'Bắp caramel giòn ngọt size L.', 79000.00, 'Food', 'https://cdn.cah.local/foods/popcorn-caramel.jpg', TRUE),
    ('Bắp Phô Mai Lớn', 'Bắp phủ bột phô mai đậm vị size L.', 79000.00, 'Food', 'https://cdn.cah.local/foods/popcorn-cheese.jpg', TRUE),
    ('Hotdog Phô Mai', 'Bánh hotdog nóng kèm xúc xích và sốt phô mai.', 59000.00, 'Food', 'https://cdn.cah.local/foods/hotdog-cheese.jpg', TRUE),
    ('Nachos Salsa', 'Nachos giòn ăn kèm sốt salsa cà chua.', 65000.00, 'Food', 'https://cdn.cah.local/foods/nachos-salsa.jpg', TRUE),
    ('Khoai Tây Lắc Phô Mai', 'Khoai tây chiên lắc phô mai.', 55000.00, 'Food', 'https://cdn.cah.local/foods/fries-cheese.jpg', TRUE),
    ('Gà Popcorn', 'Gà viên chiên giòn vừa ăn trong rạp.', 69000.00, 'Food', 'https://cdn.cah.local/foods/chicken-popcorn.jpg', TRUE),
    ('Snack Rong Biển', 'Snack rong biển đóng gói.', 35000.00, 'Food', 'https://cdn.cah.local/foods/seaweed-snack.jpg', TRUE),
    ('Coca-Cola M', 'Nước ngọt Coca-Cola size M.', 39000.00, 'Drink', 'https://cdn.cah.local/foods/coke-m.jpg', TRUE),
    ('Coca-Cola L', 'Nước ngọt Coca-Cola size L.', 45000.00, 'Drink', 'https://cdn.cah.local/foods/coke-l.jpg', TRUE),
    ('Sprite M', 'Nước ngọt Sprite size M.', 39000.00, 'Drink', 'https://cdn.cah.local/foods/sprite-m.jpg', TRUE),
    ('Fanta Cam M', 'Nước ngọt Fanta vị cam size M.', 39000.00, 'Drink', 'https://cdn.cah.local/foods/fanta-m.jpg', TRUE),
    ('Trà Đào Cam Sả', 'Trà đào cam sả mát lạnh.', 49000.00, 'Drink', 'https://cdn.cah.local/foods/peach-tea.jpg', TRUE),
    ('Trà Sữa Trân Châu', 'Trà sữa truyền thống kèm trân châu đen.', 59000.00, 'Drink', 'https://cdn.cah.local/foods/milk-tea.jpg', TRUE),
    ('Nước Suối', 'Nước suối đóng chai 500ml.', 25000.00, 'Drink', 'https://cdn.cah.local/foods/water.jpg', TRUE),
    ('Cà Phê Sữa Đá', 'Cà phê sữa đá Việt Nam.', 45000.00, 'Drink', 'https://cdn.cah.local/foods/milk-coffee.jpg', TRUE),
    ('Matcha Latte', 'Matcha latte đá size M.', 59000.00, 'Drink', 'https://cdn.cah.local/foods/matcha-latte.jpg', TRUE),
    ('Bắp Vị Rong Biển', 'Bắp rang vị rong biển theo mùa.', 75000.00, 'Food', 'https://cdn.cah.local/foods/popcorn-seaweed.jpg', TRUE),
    ('Combo Midnight Horror', '01 bắp caramel lớn và 02 Coca-Cola L cho suất khuya.', 159000.00, 'Combo', 'https://cdn.cah.local/foods/combo-midnight.jpg', TRUE)
) AS v(name, description, price, category, image_url, is_available)
WHERE NOT EXISTS (
    SELECT 1 FROM foods f WHERE LOWER(f.name) = LOWER(v.name) AND f.is_deleted = FALSE
);

INSERT INTO vouchers (code, type, value, max_discount, min_order_value, quantity, used_count, start_at, expired_at, is_active, is_deleted)
VALUES
    ('CAHNEWBIE50', 'FIXED_AMOUNT', 50000.00, NULL, 150000.00, 500, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-12-31 23:59:59', TRUE, FALSE),
    ('MOVIENIGHT15', 'PERCENT', 15.00, 60000.00, 200000.00, 800, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-08-31 23:59:59', TRUE, FALSE),
    ('WEEKDAY25K', 'FIXED_AMOUNT', 25000.00, NULL, 100000.00, 1200, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-09-30 23:59:59', TRUE, FALSE),
    ('FAMILY20', 'PERCENT', 20.00, 100000.00, 350000.00, 300, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-12-31 23:59:59', TRUE, FALSE),
    ('IMAX80K', 'FIXED_AMOUNT', 80000.00, NULL, 300000.00, 250, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-10-31 23:59:59', TRUE, FALSE),
    ('DORAEMONKIDS', 'PERCENT', 10.00, 40000.00, 120000.00, 600, 0, TIMESTAMP '2026-05-15 00:00:00', TIMESTAMP '2026-07-31 23:59:59', TRUE, FALSE),
    ('FOODCOMBO30K', 'FIXED_AMOUNT', 30000.00, NULL, 180000.00, 700, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-12-31 23:59:59', TRUE, FALSE),
    ('SUMMER2026', 'PERCENT', 12.00, 70000.00, 220000.00, 1000, 0, TIMESTAMP '2026-06-01 00:00:00', TIMESTAMP '2026-08-15 23:59:59', TRUE, FALSE),
    ('STUDENT45K', 'FIXED_AMOUNT', 45000.00, NULL, 160000.00, 500, 0, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-11-30 23:59:59', TRUE, FALSE),
    ('PASTAPRIL20', 'PERCENT', 20.00, 50000.00, 200000.00, 100, 0, TIMESTAMP '2026-04-01 00:00:00', TIMESTAMP '2026-04-30 23:59:59', FALSE, FALSE),
    ('SOLDOUTTEST', 'FIXED_AMOUNT', 20000.00, NULL, 100000.00, 10, 10, TIMESTAMP '2026-05-01 00:00:00', TIMESTAMP '2026-12-31 23:59:59', TRUE, FALSE)
ON CONFLICT (code) DO NOTHING;

-- =============================================================
-- 5. Promotion articles
-- =============================================================

INSERT INTO promotion_articles (title, image_url, content, created_at, updated_at, is_active, is_deleted)
SELECT v.title, v.image_url, v.content, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, TRUE, FALSE
FROM (VALUES
    ('Tuần lễ bom tấn tháng 5 tại CAH Cinema', 'https://cdn.cah.local/promotions/may-blockbuster.jpg', 'Đặt vé các suất chiếu Michael, Mortal Kombat II và Thẩm Mỹ Viện Âm Phủ để nhận ưu đãi bắp nước trong tuần lễ bom tấn.'),
    ('Combo Doraemon Kids cho cả gia đình', 'https://cdn.cah.local/promotions/doraemon-kids.jpg', 'Combo trẻ em phiên bản giới hạn dành cho các suất chiếu phim hoạt hình và gia đình.'),
    ('Đêm IMAX: Trải nghiệm màn hình lớn', 'https://cdn.cah.local/promotions/imax-night.jpg', 'Ưu đãi đặc biệt cho phòng IMAX vào các suất tối thứ Sáu, thứ Bảy và Chủ nhật.'),
    ('Movie Night 15% cho hội bạn thân', 'https://cdn.cah.local/promotions/movie-night.jpg', 'Nhập mã MOVIENIGHT15 khi đặt vé từ 200.000đ để nhận ưu đãi tối đa 60.000đ.'),
    ('Ưu đãi sinh viên giữa tuần', 'https://cdn.cah.local/promotions/student-weekday.jpg', 'Các suất chiếu từ thứ Hai đến thứ Năm có thêm voucher STUDENT45K cho đơn đủ điều kiện.'),
    ('Mùa hè phiêu lưu cùng CAH', 'https://cdn.cah.local/promotions/summer-adventure.jpg', 'Chuỗi phim hoạt hình, gia đình và phiêu lưu được lên lịch dày đặc trong mùa hè 2026.'),
    ('Horror Midnight: suất khuya rùng rợn', 'https://cdn.cah.local/promotions/horror-midnight.jpg', 'Các phim kinh dị và thriller có suất chiếu khuya cùng combo Midnight Horror.'),
    ('Đặt sớm phim sắp chiếu', 'https://cdn.cah.local/promotions/coming-soon.jpg', 'Theo dõi lịch chiếu các phim sắp ra mắt để chọn ghế đẹp ngay khi mở bán.')
) AS v(title, image_url, content)
WHERE NOT EXISTS (
    SELECT 1 FROM promotion_articles pa WHERE LOWER(pa.title) = LOWER(v.title) AND pa.is_deleted = FALSE
);

-- =============================================================
-- 6. Showtimes from 2026-05-09 to 2026-06-07
-- =============================================================

WITH target_rooms AS (
    SELECT r.room_id, r.room_name, c.cinema_id
    FROM rooms r
    JOIN cinemas c ON c.cinema_id = r.cinema_id
    WHERE c.name LIKE 'CAH Cinema%'
      AND r.is_deleted = FALSE
), slots AS (
    SELECT * FROM (VALUES
        (1, TIME '08:15:00', 0),
        (2, TIME '12:00:00', 1),
        (3, TIME '15:45:00', 2),
        (4, TIME '19:30:00', 3)
    ) AS s(slot_no, start_clock, movie_offset)
), movie_pool AS (
    SELECT
        m.movie_id,
        m.duration,
        ROW_NUMBER() OVER (ORDER BY m.release_date DESC, m.movie_id) AS rn,
        COUNT(*) OVER () AS total_movies
    FROM movies m
    WHERE m.title IN (
        'Michael',
        'Mortal Kombat II',
        'The Mandalorian and Grogu',
        'The Sheep Detectives',
        'Yêu Nữ Thích Hàng Hiệu 2',
        'Doraemon: Nobita Và Cuộc Phiêu Lưu Ở Thế Giới Tranh',
        'Thám Tử Kiên: Kỳ Án Không Đầu',
        'Lật Mặt 9: Vòng Xoáy Gia Đình',
        'Supergirl: Woman of Tomorrow',
        'Toy Story 5',
        'Moana: Live Action',
        'Scream 7',
        'Project Hail Mary',
        'Minions & Monsters',
        'Thẩm Mỹ Viện Âm Phủ',
        'Trạng Quỳnh Nhí: Truyền Thuyết Hồ Sen',
        'Ballerina',
        'Mission: Impossible - The Final Reckoning',
        'How to Train Your Dragon',
        'Elio',
        'F1 The Movie',
        'Jurassic World Rebirth',
        'The Fantastic Four: First Steps',
        'Wicked: For Good',
        'Avatar: Fire and Ash'
    )
    AND m.is_deleted = FALSE
), schedule_seed AS (
    SELECT
        tr.room_id,
        mp.movie_id,
        CASE
            WHEN tr.room_name LIKE '%IMAX%' THEN 'IMAX'
            WHEN MOD((EXTRACT(DOY FROM d.day_date)::INT + s.slot_no + tr.room_id)::INT, 5) = 0 THEN '3D'
            ELSE '2D'
        END AS format,
        (d.day_date::DATE + s.start_clock) AS start_time,
        (d.day_date::DATE + s.start_clock + (mp.duration || ' minutes')::INTERVAL) AS end_time,
        CASE
            WHEN tr.room_name LIKE '%IMAX%' THEN 145000.00
            WHEN MOD((EXTRACT(DOY FROM d.day_date)::INT + s.slot_no + tr.room_id)::INT, 5) = 0 THEN 115000.00
            WHEN s.slot_no = 1 THEN 75000.00
            WHEN s.slot_no >= 4 THEN 105000.00
            ELSE 90000.00
        END AS base_price
    FROM target_rooms tr
    CROSS JOIN generate_series(DATE '2026-05-09', DATE '2026-06-07', INTERVAL '1 day') AS d(day_date)
    CROSS JOIN slots s
    JOIN movie_pool mp
      ON mp.rn = MOD((EXTRACT(DOY FROM d.day_date)::INT + tr.room_id::INT + s.movie_offset), mp.total_movies) + 1
)
INSERT INTO showtimes (room_id, movie_id, format, start_time, end_time, base_price, is_deleted, status)
SELECT ss.room_id, ss.movie_id, ss.format, ss.start_time, ss.end_time, ss.base_price, FALSE, 'AVAILABLE'
FROM schedule_seed ss
WHERE NOT EXISTS (
    SELECT 1 FROM showtimes st
    WHERE st.room_id = ss.room_id
      AND st.start_time = ss.start_time
      AND st.is_deleted = FALSE
);

COMMIT;
